import { addDays, startOfDay } from 'date-fns';

import type { EventRow } from './types';

interface MockTemplate {
  slug: string;
  title: string;
  venue: string;
  district: string;
  address: string;
  lat: number;
  lng: number;
  /** Weekdays the night starts on (0 = Sunday ... 6 = Saturday). */
  days: number[];
  /** Hour the doors open. Values below 6 belong to the previous night. */
  startHour: number;
  durationHours: number;
  /** Raw music genre tags — mapped onto canonical genres in `lib/taxonomy`. */
  category: string[];
  /** Raw vibe tags — mapped onto canonical vibes in `lib/taxonomy`. */
  vibe_tags: string[];
  lineup: string[];
  priceMin: number | null;
  priceMax: number | null;
  isFree: boolean;
  description: string;
}

const TEMPLATES: MockTemplate[] = [
  {
    slug: 'klubnacht-hardgroove',
    title: 'Klubnacht: Hardgroove Sessions',
    venue: 'Berghain / Panorama Bar',
    district: 'Friedrichshain',
    address: 'Am Wriezener Bahnhof, 10243 Berlin',
    lat: 52.5111,
    lng: 13.4432,
    days: [5, 6],
    startHour: 0,
    durationHours: 20,
    category: ['hardgroove', 'techno', 'house'],
    vibe_tags: ['dancing', 'underground', 'afterhours'],
    lineup: ['Nadia Ksaiba', 'Setaoc Mass', 'Kobosil'],
    priceMin: 20,
    priceMax: 25,
    isFree: false,
    description:
      'Three floors, no phone photos, open end. Hard groove in the main room, house and disco upstairs in the Panorama Bar.',
  },
  {
    slug: 'watergate-deep',
    title: 'Deep Waters',
    venue: 'Watergate',
    district: 'Kreuzberg',
    address: 'Falckensteinstraße 49, 10997 Berlin',
    lat: 52.5015,
    lng: 13.4443,
    days: [4, 5, 6],
    startHour: 23,
    durationHours: 9,
    category: ['deep-house', 'melodic-techno', 'progressive'],
    vibe_tags: ['dancing', 'dressy'],
    lineup: ['Ellen Allien', 'Marvin & Guy'],
    priceMin: 18,
    priceMax: 22,
    isFree: false,
    description:
      'Panorama window onto the Spree, warm deep house and a floor that runs until sunrise.',
  },
  {
    slug: 'sisyphos-hammahalle',
    title: 'Hammahalle Open Air',
    venue: 'Sisyphos',
    district: 'Lichtenberg',
    address: 'Hauptstraße 15, 10317 Berlin',
    lat: 52.49,
    lng: 13.493,
    days: [5, 6],
    startHour: 22,
    durationHours: 30,
    category: ['techno', 'minimal', 'psytrance'],
    vibe_tags: ['dancing', 'openair', 'afterhours', 'underground'],
    lineup: ['Nils Hoffmann', 'Perel'],
    priceMin: 20,
    priceMax: null,
    isFree: false,
    description:
      'A former dog biscuit factory with a circus tent and a sand beach. Runs straight through to Monday morning.',
  },
  {
    slug: 'renate-indie',
    title: 'Wild Nights: Indie & Wave',
    venue: 'Salon zur Wilden Renate',
    district: 'Friedrichshain',
    address: 'Alt-Stralau 70, 10245 Berlin',
    lat: 52.5045,
    lng: 13.46,
    days: [4, 6],
    startHour: 23,
    durationHours: 8,
    category: ['indie', 'darkwave', 'post-punk'],
    vibe_tags: ['dancing', 'underground', 'social'],
    lineup: ['DJ Kaspar', 'Lena Vinyl'],
    priceMin: 12,
    priceMax: 15,
    isFree: false,
    description:
      'A maze of an old flat with three small floors. Indie and wave upstairs, fast electro in the cellar.',
  },
  {
    slug: 'lido-livekonzert',
    title: 'Lido Live: New Guitar Bands',
    venue: 'Lido',
    district: 'Kreuzberg',
    address: 'Cuvrystraße 7, 10997 Berlin',
    lat: 52.4977,
    lng: 13.4451,
    days: [2, 4, 5],
    startHour: 20,
    durationHours: 4,
    category: ['indie-rock', 'shoegaze', 'alternative'],
    vibe_tags: ['live', 'social'],
    lineup: ['Fenster', 'Sofia Portanet'],
    priceMin: 16,
    priceMax: 19,
    isFree: false,
    description:
      'Old cinema hall, short way to the stage. Afterwards the house crew plays records for two more hours.',
  },
  {
    slug: 'so36-punk',
    title: 'Punk Night at SO36',
    venue: 'SO36',
    district: 'Kreuzberg',
    address: 'Oranienstraße 190, 10999 Berlin',
    lat: 52.5028,
    lng: 13.4218,
    days: [3, 5],
    startHour: 21,
    durationHours: 5,
    category: ['punk', 'hardcore-punk', 'metal'],
    vibe_tags: ['live', 'underground'],
    lineup: ['Radikale Söhne', 'Betonliebe'],
    priceMin: 14,
    priceMax: null,
    isFree: false,
    description: 'Sweat, beer, stage dives. An institution since 1978 and still loud.',
  },
  {
    slug: 'claerchens-tanz',
    title: 'Ballroom Dance Night',
    venue: 'Clärchens Ballhaus',
    district: 'Mitte',
    address: 'Auguststraße 24, 10117 Berlin',
    lat: 52.5253,
    lng: 13.397,
    days: [0, 2, 4],
    startHour: 20,
    durationHours: 5,
    category: ['soul', 'jazz', 'pop'],
    vibe_tags: ['dressy', 'social', 'dancing'],
    lineup: ['Ballhaus Ensemble'],
    priceMin: 10,
    priceMax: null,
    isFree: false,
    description:
      'Mirror hall, parquet floor, live band. No dress code, but most people make an effort.',
  },
  {
    slug: 'kater-blau',
    title: 'Katerkonzert',
    venue: 'Kater Blau',
    district: 'Mitte',
    address: 'Holzmarktstraße 25, 10243 Berlin',
    lat: 52.5116,
    lng: 13.4256,
    days: [5, 6, 0],
    startHour: 23,
    durationHours: 24,
    category: ['house', 'techno', 'disco'],
    vibe_tags: ['dancing', 'openair', 'afterhours'],
    lineup: ['Nu Zau', 'Undercatt'],
    priceMin: 18,
    priceMax: null,
    isFree: false,
    description: 'Wooden terrace right on the river, live musicians in between the DJ sets.',
  },
  {
    slug: 'gretchen-dnb',
    title: 'Bassline: Drum & Bass Night',
    venue: 'Gretchen',
    district: 'Kreuzberg',
    address: 'Obentrautstraße 19, 10963 Berlin',
    lat: 52.4949,
    lng: 13.3986,
    days: [4, 6],
    startHour: 23,
    durationHours: 7,
    category: ['dnb', 'jungle', 'dubstep'],
    vibe_tags: ['dancing', 'underground'],
    lineup: ['Alix Perez', 'Skeptical'],
    priceMin: 15,
    priceMax: 18,
    isFree: false,
    description: 'A vaulted cellar with a serious rig. Pure bass music, no filler.',
  },
  {
    slug: 'yaam-afro',
    title: 'Afrobeats & Amapiano by the Water',
    venue: 'YAAM',
    district: 'Friedrichshain',
    address: 'An der Schillingbrücke 3, 10243 Berlin',
    lat: 52.5052,
    lng: 13.4335,
    days: [5, 6, 0],
    startHour: 21,
    durationHours: 7,
    category: ['afrobeats', 'amapiano', 'dancehall'],
    vibe_tags: ['dancing', 'openair', 'social'],
    lineup: ['DJ Tunde', 'Selecta Mo'],
    priceMin: 12,
    priceMax: null,
    isFree: false,
    description: 'Sand, river view, grill smoke. Later the inside floor turns into the dancefloor.',
  },
  {
    slug: 'klunkerkranich-sunset',
    title: 'Rooftop Sunset',
    venue: 'Klunkerkranich',
    district: 'Neukölln',
    address: 'Karl-Marx-Straße 66, 12043 Berlin',
    lat: 52.4795,
    lng: 13.438,
    days: [1, 2, 3, 4, 5, 6, 0],
    startHour: 19,
    durationHours: 5,
    category: ['soul', 'funk', 'nu-jazz'],
    vibe_tags: ['chill', 'openair', 'social', 'dressy'],
    lineup: ['Rooftop Selectors'],
    priceMin: 4,
    priceMax: null,
    isFree: false,
    description:
      'Car park roof above Neukölln. Wide view, warm records, no pressure to dance — but you can.',
  },
  {
    slug: 'birgit-bier',
    title: 'Garden Party: Disco & Italo',
    venue: 'Birgit & Bier',
    district: 'Kreuzberg',
    address: 'Schleusenufer 3, 10997 Berlin',
    lat: 52.4966,
    lng: 13.4479,
    days: [5, 6],
    startHour: 22,
    durationHours: 9,
    category: ['italo-disco', 'nu-disco', 'tech-house'],
    vibe_tags: ['dancing', 'openair', 'dressy'],
    lineup: ['Discodromo', 'Nadia Struiwigh'],
    priceMin: 15,
    priceMax: null,
    isFree: false,
    description: 'Carousel, fairy lights, open-air floor. The summer classic by the canal.',
  },
  {
    slug: 'about-blank-queer',
    title: 'Buttons: Queer Rave',
    venue: 'about blank',
    district: 'Friedrichshain',
    address: 'Markgrafendamm 24c, 10245 Berlin',
    lat: 52.504,
    lng: 13.468,
    days: [6],
    startHour: 23,
    durationHours: 14,
    category: ['techno', 'electro', 'breakcore'],
    vibe_tags: ['queer', 'dancing', 'underground', 'afterhours'],
    lineup: ['Ziúr', 'Lag Bo'],
    priceMin: 16,
    priceMax: null,
    isFree: false,
    description:
      'Awareness team, garden floor, uncompromising sound. A queer night with an attitude.',
  },
  {
    slug: 'tresor-globus',
    title: 'Tresor Night',
    venue: 'Tresor',
    district: 'Mitte',
    address: 'Köpenicker Straße 70, 10179 Berlin',
    lat: 52.5107,
    lng: 13.4198,
    days: [3, 5, 6],
    startHour: 0,
    durationHours: 10,
    category: ['techno', 'industrial-techno', 'electro'],
    vibe_tags: ['dancing', 'underground', 'dark'],
    lineup: ['Vril', 'DJ Bone'],
    priceMin: 15,
    priceMax: 20,
    isFree: false,
    description: 'The tunnel, the fog, the strobes. Techno in its most reduced form.',
  },
  {
    slug: 'prince-charles-hiphop',
    title: 'Rap Sundays',
    venue: 'Prince Charles',
    district: 'Kreuzberg',
    address: 'Prinzenstraße 85f, 10969 Berlin',
    lat: 52.501,
    lng: 13.4106,
    days: [0, 4],
    startHour: 22,
    durationHours: 6,
    category: ['hiphop', 'rnb', 'trap'],
    vibe_tags: ['dancing', 'social', 'stylish'],
    lineup: ['DJ Nadir', 'Miss Cee'],
    priceMin: 12,
    priceMax: null,
    isFree: false,
    description: 'A former swimming pool as a dancefloor. Curated rap sets, nothing else needed.',
  },
  {
    slug: 'monarch-electro',
    title: 'Monarch: Electro & EBM',
    venue: 'Monarch',
    district: 'Kreuzberg',
    address: 'Skalitzer Straße 134, 10999 Berlin',
    lat: 52.5006,
    lng: 13.4222,
    days: [2, 4, 5],
    startHour: 22,
    durationHours: 6,
    category: ['electro', 'ebm', 'minimal-wave'],
    vibe_tags: ['dancing', 'underground', 'social'],
    lineup: ['Sarah Farina', 'Bad Stream'],
    priceMin: 8,
    priceMax: null,
    isFree: false,
    description: 'One room, big windows onto the U1 tracks. The most honest small club in town.',
  },
  {
    slug: 'arkaoda-experimental',
    title: 'Modular Nights',
    venue: 'Arkaoda',
    district: 'Neukölln',
    address: 'Karl-Marx-Platz 16, 12043 Berlin',
    lat: 52.483,
    lng: 13.429,
    days: [1, 3],
    startHour: 20,
    durationHours: 5,
    category: ['ambient', 'experimental', 'modular'],
    vibe_tags: ['chill', 'underground', 'live'],
    lineup: ['Grand River', 'Konvex'],
    priceMin: 10,
    priceMax: null,
    isFree: false,
    description:
      'Sit down, listen, be surprised. Live electronics without a four-to-the-floor kick.',
  },
  {
    slug: 'zig-zag-jazz',
    title: 'Jazz Club Session',
    venue: 'ZigZag Jazz Club',
    district: 'Schöneberg',
    address: 'Hauptstraße 89, 12159 Berlin',
    lat: 52.4762,
    lng: 13.3512,
    days: [1, 2, 3, 4],
    startHour: 20,
    durationHours: 4,
    category: ['jazz', 'bebop', 'nu-jazz'],
    vibe_tags: ['chill', 'live', 'dressy'],
    lineup: ['Berlin Jazz Collective'],
    priceMin: 14,
    priceMax: 18,
    isFree: false,
    description: 'Small stage, good food, a real jam session at the end of the night.',
  },
  {
    slug: 'mein-haus-am-see',
    title: 'Bar Session: Soul & Boogie',
    venue: 'Mein Haus am See',
    district: 'Mitte',
    address: 'Brunnenstraße 197, 10119 Berlin',
    lat: 52.5285,
    lng: 13.4009,
    days: [1, 2, 3, 4, 5, 6, 0],
    startHour: 21,
    durationHours: 7,
    category: ['soul', 'boogie', 'pop'],
    vibe_tags: ['chill', 'social', 'bar'],
    lineup: ['Rotating guests'],
    priceMin: null,
    priceMax: null,
    isFree: true,
    description: 'Grandstand seating, coffee to cocktails, always open. No entry fee, no stress.',
  },
  {
    slug: 'buck-and-breck',
    title: 'Cocktail Hour in the Back Room',
    venue: 'Buck and Breck',
    district: 'Mitte',
    address: 'Brunnenstraße 177, 10119 Berlin',
    lat: 52.5306,
    lng: 13.4023,
    days: [2, 3, 4, 5, 6],
    startHour: 19,
    durationHours: 5,
    category: ['jazz', 'soul'],
    vibe_tags: ['dressy', 'chill', 'cocktail'],
    lineup: [],
    priceMin: null,
    priceMax: null,
    isFree: true,
    description: 'Fourteen seats, classic drinks, dimmed light. Reservation only.',
  },
  {
    slug: 'schmutziges-hobby',
    title: 'Drag Bingo',
    venue: 'Zum schmutzigen Hobby',
    district: 'Friedrichshain',
    address: 'Revaler Straße 99, 10245 Berlin',
    lat: 52.504,
    lng: 13.455,
    days: [1, 3, 6],
    startHour: 21,
    durationHours: 4,
    category: ['pop', 'schlager', 'charts'],
    vibe_tags: ['queer', 'comedy', 'social', 'chill'],
    lineup: ['Nina Queer'],
    priceMin: null,
    priceMax: null,
    isFree: true,
    description: 'Loud, camp and warm-hearted. Bingo with drag hosts and cheap shots.',
  },
  {
    slug: 'astra-konzert',
    title: 'Astra Concert Night',
    venue: 'Astra Kulturhaus',
    district: 'Friedrichshain',
    address: 'Revaler Straße 99, 10245 Berlin',
    lat: 52.5051,
    lng: 13.4497,
    days: [2, 3, 5],
    startHour: 20,
    durationHours: 4,
    category: ['indie', 'rock', 'pop'],
    vibe_tags: ['live', 'social'],
    lineup: ['Kraftklub', 'Support: Blond'],
    priceMin: 28,
    priceMax: 38,
    isFree: false,
    description: 'GDR charm, a big hall and a loud crowd. Aftershow next door.',
  },
  {
    slug: 'frannz-90s',
    title: '90s & 2000s Party',
    venue: 'Frannz Club',
    district: 'Prenzlauer Berg',
    address: 'Schönhauser Allee 36, 10435 Berlin',
    lat: 52.539,
    lng: 13.411,
    days: [5, 6],
    startHour: 23,
    durationHours: 6,
    category: ['90s', '2000s', 'charts', 'hiphop'],
    vibe_tags: ['dancing', 'social', 'kennenlernen'],
    lineup: ['DJ Retro'],
    priceMin: 10,
    priceMax: null,
    isFree: false,
    description: 'Sing along, garden floor in summer. Zero attitude.',
  },
  {
    slug: 'loophole-experimental',
    title: 'Loophole: Noise & Readings',
    venue: 'Loophole',
    district: 'Neukölln',
    address: 'Boddinstraße 60, 12053 Berlin',
    lat: 52.488,
    lng: 13.423,
    days: [1, 2, 4],
    startHour: 20,
    durationHours: 5,
    category: ['noise', 'experimental', 'drone'],
    vibe_tags: ['underground', 'chill', 'poetry', 'live'],
    lineup: ['Open stage'],
    priceMin: 5,
    priceMax: null,
    isFree: false,
    description:
      'A basement room with a changing programme between readings, noise and performance.',
  },
  {
    slug: 'ritter-butzke',
    title: 'Ritter Butzke Night',
    venue: 'Ritter Butzke',
    district: 'Kreuzberg',
    address: 'Ritterstraße 24, 10969 Berlin',
    lat: 52.5029,
    lng: 13.4083,
    days: [5, 6],
    startHour: 23,
    durationHours: 9,
    category: ['tech-house', 'house', 'melodic-techno'],
    vibe_tags: ['dancing', 'dressy'],
    lineup: ['Fritz Kalkbrenner', 'Nu Sky'],
    priceMin: 18,
    priceMax: 22,
    isFree: false,
    description: 'Old factory, four rooms, plenty of decoration. Accessible house for long nights.',
  },
  {
    slug: 'sameheads-latin',
    title: 'Baile & Reggaeton',
    venue: 'Sameheads',
    district: 'Neukölln',
    address: 'Richardstraße 10, 12043 Berlin',
    lat: 52.4795,
    lng: 13.435,
    days: [4, 6],
    startHour: 23,
    durationHours: 7,
    category: ['reggaeton', 'baile-funk', 'gqom'],
    vibe_tags: ['dancing', 'social', 'underground'],
    lineup: ['La Fraîcheur', 'DJ Perreo'],
    priceMin: 8,
    priceMax: null,
    isFree: false,
    description: 'Shop front upstairs, sweat box downstairs. Tight dancefloor, big mood.',
  },
  {
    slug: 'privatclub-indie',
    title: 'Indie Disco',
    venue: 'Privatclub',
    district: 'Kreuzberg',
    address: 'Skalitzer Straße 85, 10997 Berlin',
    lat: 52.4989,
    lng: 13.4227,
    days: [5],
    startHour: 23,
    durationHours: 6,
    category: ['indie', 'britpop', 'post-punk', 'alternative'],
    vibe_tags: ['dancing', 'social', 'kennenlernen'],
    lineup: ['DJ Anorak'],
    priceMin: 9,
    priceMax: null,
    isFree: false,
    description:
      'From The Strokes to Fontaines D.C. If you like guitars and dancing, this is your room.',
  },
  {
    slug: 'saeaelchen-live',
    title: 'Säälchen Showcase',
    venue: 'Säälchen am Holzmarkt',
    district: 'Mitte',
    address: 'Holzmarktstraße 25, 10243 Berlin',
    lat: 52.5107,
    lng: 13.429,
    days: [2, 3, 4],
    startHour: 20,
    durationHours: 4,
    category: ['dream-pop', 'indie', 'ambient'],
    vibe_tags: ['live', 'chill', 'openair'],
    lineup: ['Newcomer showcase'],
    priceMin: 12,
    priceMax: null,
    isFree: false,
    description: 'Wooden hall by the water, seated audience, beers in the garden afterwards.',
  },
  {
    slug: 'ohm-ambient',
    title: 'OHM: Late Ambient',
    venue: 'OHM',
    district: 'Mitte',
    address: 'Köpenicker Straße 70, 10179 Berlin',
    lat: 52.5105,
    lng: 13.4192,
    days: [0, 3],
    startHour: 1,
    durationHours: 7,
    category: ['ambient', 'idm', 'experimental'],
    vibe_tags: ['afterhours', 'chill', 'underground'],
    lineup: ['Ambient Kollektiv'],
    priceMin: 10,
    priceMax: null,
    isFree: false,
    description: 'Former battery house. Cushions, fog and slow frequencies until morning.',
  },
  {
    slug: 'kantine-quiz',
    title: 'Pub Quiz & Karaoke',
    venue: 'Kantine am Berghain',
    district: 'Friedrichshain',
    address: 'Am Wriezener Bahnhof, 10243 Berlin',
    lat: 52.5115,
    lng: 13.4425,
    days: [1, 2],
    startHour: 19,
    durationHours: 4,
    category: ['pop', '80s', 'charts'],
    vibe_tags: ['quiz', 'karaoke', 'kennenlernen', 'chill'],
    lineup: ['Quizmaster Ben'],
    priceMin: 3,
    priceMax: null,
    isFree: false,
    description: 'Teams of up to six, open karaoke afterwards. Worth signing up early.',
  },
  {
    slug: 'void-hardtechno',
    title: 'Void: Hard Techno & Hardstyle',
    venue: 'Void Club',
    district: 'Treptow',
    address: 'Am Flutgraben 3, 12435 Berlin',
    lat: 52.4967,
    lng: 13.4514,
    days: [5, 6],
    startHour: 23,
    durationHours: 8,
    category: ['hard-techno', 'hardstyle', 'schranz'],
    vibe_tags: ['dancing', 'underground', 'dark'],
    lineup: ['Rebekah', 'Lilly Palmer'],
    priceMin: 16,
    priceMax: 20,
    isFree: false,
    description: 'Fast BPMs, no melodies, concrete walls. Bring water.',
  },
  {
    slug: 'oxi-garage',
    title: 'Oxi: UK Garage & Bassline',
    venue: 'Oxi Club',
    district: 'Wedding',
    address: 'Gerichtstraße 65, 13347 Berlin',
    lat: 52.5443,
    lng: 13.3745,
    days: [4, 5],
    startHour: 23,
    durationHours: 7,
    category: ['uk-garage', '2step', 'grime'],
    vibe_tags: ['dancing', 'social'],
    lineup: ['Sherelle', 'DJ Q'],
    priceMin: 13,
    priceMax: null,
    isFree: false,
    description: 'Shuffling, MC on the mic, sub-bass in your chest. Wedding at its best.',
  },
  {
    slug: 'goldrand-trance',
    title: 'Goldrand: Trance Revival',
    venue: 'Goldrand',
    district: 'Charlottenburg',
    address: 'Kantstraße 148, 10623 Berlin',
    lat: 52.5045,
    lng: 13.3223,
    days: [5, 6],
    startHour: 23,
    durationHours: 7,
    category: ['trance', 'hypertrance', 'progressive-trance'],
    vibe_tags: ['dancing', 'dressy', 'social'],
    lineup: ['Kiara Scuro', 'Elite Mane'],
    priceMin: 14,
    priceMax: 18,
    isFree: false,
    description: 'Lasers, hands in the air, unashamed euphoria. West Berlin does trance again.',
  },
  {
    slug: 'kesselhaus-kpop',
    title: 'K-Pop & J-Pop Night',
    venue: 'Kesselhaus',
    district: 'Prenzlauer Berg',
    address: 'Knaackstraße 97, 10435 Berlin',
    lat: 52.5321,
    lng: 13.4197,
    days: [6],
    startHour: 22,
    durationHours: 6,
    category: ['kpop', 'jpop', 'city-pop'],
    vibe_tags: ['dancing', 'social', 'kennenlernen'],
    lineup: ['DJ Hana'],
    priceMin: 12,
    priceMax: null,
    isFree: false,
    description: 'Random play dance, light sticks welcome, big singalongs.',
  },
  {
    slug: 'gruener-salon-comedy',
    title: 'English Stand-Up Night',
    venue: 'Grüner Salon',
    district: 'Mitte',
    address: 'Rosa-Luxemburg-Platz, 10178 Berlin',
    lat: 52.5273,
    lng: 13.4113,
    days: [2, 3],
    startHour: 20,
    durationHours: 3,
    category: ['pop', 'jazz'],
    vibe_tags: ['comedy', 'standup', 'chill', 'social'],
    lineup: ['Rotating line-up'],
    priceMin: 12,
    priceMax: null,
    isFree: false,
    description: 'Velvet chairs, seven comedians, one microphone. English all night.',
  },
  {
    slug: 'holzmarkt-balkan',
    title: 'Balkan Brass Riot',
    venue: 'Holzmarkt Pampa',
    district: 'Mitte',
    address: 'Holzmarktstraße 25, 10243 Berlin',
    lat: 52.5112,
    lng: 13.4271,
    days: [4, 6],
    startHour: 21,
    durationHours: 6,
    category: ['balkan', 'brass', 'gypsy', 'folk'],
    vibe_tags: ['dancing', 'live', 'openair', 'social'],
    lineup: ['Brass Riot Orchestra'],
    priceMin: 10,
    priceMax: 14,
    isFree: false,
    description: 'A brass band on a river deck, then records until the neighbours complain.',
  },
];

/**
 * Deterministic demo programme used while the Supabase tables are still empty.
 * Rows are shaped exactly like the `events_feed` view.
 */
export function buildMockEvents(from: Date = new Date(), days = 21): EventRow[] {
  const today = startOfDay(from);
  const events: EventRow[] = [];

  for (let offset = 0; offset < days; offset += 1) {
    const nightDate = addDays(today, offset);
    const weekday = nightDate.getDay();

    for (const template of TEMPLATES) {
      if (!template.days.includes(weekday)) continue;

      const startsAt = new Date(nightDate);
      const dayShift = template.startHour < 6 ? 1 : 0;
      startsAt.setDate(startsAt.getDate() + dayShift);
      startsAt.setHours(template.startHour, 0, 0, 0);

      const endsAt = new Date(startsAt.getTime() + template.durationHours * 60 * 60 * 1000);

      events.push({
        id: `mock:${template.slug}:${offset}`,
        title: template.title,
        description_ours: template.description,
        starts_at: startsAt.toISOString(),
        ends_at: endsAt.toISOString(),
        doors_at: null,
        venue_name: template.venue,
        address: template.address,
        district: template.district,
        venue_homepage: null,
        price_min: template.priceMin,
        price_max: template.priceMax,
        is_free: template.isFree,
        ticket_url: null,
        source_url: null,
        category: template.category,
        vibe_tags: template.vibe_tags,
        lineup: template.lineup,
        image_url: null,
        status: 'active',
        latitude: template.lat,
        longitude: template.lng,
        image_source: null,
        organizer_name: template.venue,
        organizer_image_url: null,
        organizer_type: 'venue',
      });
    }
  }

  return events.sort(
    (left, right) => new Date(left.starts_at).getTime() - new Date(right.starts_at).getTime(),
  );
}
