import { addDays, startOfDay } from 'date-fns';

import type { EventRow } from './types';

interface MockTemplate {
  slug: string;
  title: string;
  venue: string;
  district: string;
  address: string;
  lat: number;
  lng: number;
  /** Weekdays the night starts on (0 = Sunday ... 6 = Saturday). */
  days: number[];
  /** Hour the doors open. Values below 6 belong to the previous night. */
  startHour: number;
  durationHours: number;
  category: string[];
  vibe_tags: string[];
  lineup: string[];
  priceMin: number | null;
  priceMax: number | null;
  isFree: boolean;
  description: string;
}

const TEMPLATES: MockTemplate[] = [
  {
    slug: 'klubnacht-hardgroove',
    title: 'Klubnacht: Hardgroove Sessions',
    venue: 'Berghain / Panorama Bar',
    district: 'Friedrichshain',
    address: 'Am Wriezener Bahnhof, 10243 Berlin',
    lat: 52.5111,
    lng: 13.4432,
    days: [5, 6],
    startHour: 0,
    durationHours: 20,
    category: ['techno', 'hardgroove'],
    vibe_tags: ['tanzen', 'underground', 'afterhour'],
    lineup: ['Nadia Ksaiba', 'Setaoc Mass', 'Kobosil'],
    priceMin: 20,
    priceMax: 25,
    isFree: false,
    description:
      'Drei Floors, kein Handyfoto, offenes Ende. Harter Groove im Hauptraum, House und Disco oben in der Panorama Bar.',
  },
  {
    slug: 'watergate-deep',
    title: 'Deep Waters',
    venue: 'Watergate',
    district: 'Kreuzberg',
    address: 'Falckensteinstraße 49, 10997 Berlin',
    lat: 52.5015,
    lng: 13.4443,
    days: [4, 5, 6],
    startHour: 23,
    durationHours: 9,
    category: ['house', 'deep-house', 'techno'],
    vibe_tags: ['tanzen', 'schick'],
    lineup: ['Ellen Allien', 'Marvin & Guy'],
    priceMin: 18,
    priceMax: 22,
    isFree: false,
    description:
      'Panoramafenster zur Spree, warmer Deep-House-Sound und ein Floor, der bis zum Sonnenaufgang läuft.',
  },
  {
    slug: 'sisyphos-hammahalle',
    title: 'Hammahalle Open Air',
    venue: 'Sisyphos',
    district: 'Lichtenberg',
    address: 'Hauptstraße 15, 10317 Berlin',
    lat: 52.49,
    lng: 13.493,
    days: [5, 6],
    startHour: 22,
    durationHours: 30,
    category: ['techno', 'house', 'psytrance'],
    vibe_tags: ['tanzen', 'openair', 'afterhour', 'underground'],
    lineup: ['Nils Hoffmann', 'Perel'],
    priceMin: 20,
    priceMax: null,
    isFree: false,
    description:
      'Ehemalige Hundekuchenfabrik, Zirkuszelt, Sandstrand. Läuft durch bis Montagmorgen.',
  },
  {
    slug: 'renate-indie',
    title: 'Wilde Nächte: Indie & Wave',
    venue: 'Salon zur Wilden Renate',
    district: 'Friedrichshain',
    address: 'Alt-Stralau 70, 10245 Berlin',
    lat: 52.5045,
    lng: 13.46,
    days: [4, 6],
    startHour: 23,
    durationHours: 8,
    category: ['indie', 'wave', 'post-punk'],
    vibe_tags: ['tanzen', 'underground', 'social'],
    lineup: ['DJ Kaspar', 'Lena Vinyl'],
    priceMin: 12,
    priceMax: 15,
    isFree: false,
    description:
      'Verwinkelte Altbauwohnung, drei kleine Floors. Oben Indie und Wave, unten schneller Elektro.',
  },
  {
    slug: 'lido-livekonzert',
    title: 'Lido Live: Neue Gitarrenbands',
    venue: 'Lido',
    district: 'Kreuzberg',
    address: 'Cuvrystraße 7, 10997 Berlin',
    lat: 52.4977,
    lng: 13.4451,
    days: [2, 4, 5],
    startHour: 20,
    durationHours: 4,
    category: ['indie', 'rock', 'konzert'],
    vibe_tags: ['live', 'social'],
    lineup: ['Fenster', 'Sofia Portanet'],
    priceMin: 16,
    priceMax: 19,
    isFree: false,
    description:
      'Alter Kinosaal, kurze Wege zur Bühne. Danach legt die Hausband-Crew noch zwei Stunden Platten auf.',
  },
  {
    slug: 'so36-punk',
    title: 'Punk im SO36',
    venue: 'SO36',
    district: 'Kreuzberg',
    address: 'Oranienstraße 190, 10999 Berlin',
    lat: 52.5028,
    lng: 13.4218,
    days: [3, 5],
    startHour: 21,
    durationHours: 5,
    category: ['punk', 'hardcore', 'konzert'],
    vibe_tags: ['live', 'underground'],
    lineup: ['Radikale Söhne', 'Betonliebe'],
    priceMin: 14,
    priceMax: null,
    isFree: false,
    description: 'Schweiß, Bier, Bühnenkante. Institution seit 1978 und immer noch laut.',
  },
  {
    slug: 'clärchens-tanz',
    title: 'Ballhaus Tanzabend',
    venue: 'Clärchens Ballhaus',
    district: 'Mitte',
    address: 'Auguststraße 24, 10117 Berlin',
    lat: 52.5253,
    lng: 13.397,
    days: [0, 2, 4],
    startHour: 20,
    durationHours: 5,
    category: ['soul', 'jazz', 'pop'],
    vibe_tags: ['schick', 'social', 'tanzen'],
    lineup: ['Ballhaus Ensemble'],
    priceMin: 10,
    priceMax: null,
    isFree: false,
    description:
      'Spiegelsaal, Parkett, Livekapelle. Kein Dresscode, aber die meisten machen sich fein.',
  },
  {
    slug: 'kater-blau',
    title: 'Katerkonzert',
    venue: 'Kater Blau',
    district: 'Mitte',
    address: 'Holzmarktstraße 25, 10243 Berlin',
    lat: 52.5116,
    lng: 13.4256,
    days: [5, 6, 0],
    startHour: 23,
    durationHours: 24,
    category: ['house', 'techno', 'disco'],
    vibe_tags: ['tanzen', 'openair', 'afterhour'],
    lineup: ['Nu Zau', 'Undercatt'],
    priceMin: 18,
    priceMax: null,
    isFree: false,
    description: 'Holzterrasse direkt an der Spree, Livemusik zwischen den DJ-Sets.',
  },
  {
    slug: 'gretchen-dnb',
    title: 'Bassline: Drum & Bass Night',
    venue: 'Gretchen',
    district: 'Kreuzberg',
    address: 'Obentrautstraße 19, 10963 Berlin',
    lat: 52.4949,
    lng: 13.3986,
    days: [4, 6],
    startHour: 23,
    durationHours: 7,
    category: ['dnb', 'jungle', 'bass'],
    vibe_tags: ['tanzen', 'underground'],
    lineup: ['Alix Perez', 'Skeptical'],
    priceMin: 15,
    priceMax: 18,
    isFree: false,
    description: 'Gewölbekeller mit ernsthafter Anlage. Reine Bassmusik, kein Zwischenprogramm.',
  },
  {
    slug: 'yaam-afro',
    title: 'Afrobeats & Amapiano am Wasser',
    venue: 'YAAM',
    district: 'Friedrichshain',
    address: 'An der Schillingbrücke 3, 10243 Berlin',
    lat: 52.5052,
    lng: 13.4335,
    days: [5, 6, 0],
    startHour: 21,
    durationHours: 7,
    category: ['afrobeats', 'amapiano', 'reggae'],
    vibe_tags: ['tanzen', 'openair', 'social'],
    lineup: ['DJ Tunde', 'Selecta Mo'],
    priceMin: 12,
    priceMax: null,
    isFree: false,
    description: 'Sand, Spreeblick, Grill. Später wird der Innenfloor zum Dancefloor.',
  },
  {
    slug: 'klunkerkranich-sunset',
    title: 'Sunset auf dem Dach',
    venue: 'Klunkerkranich',
    district: 'Neukölln',
    address: 'Karl-Marx-Straße 66, 12043 Berlin',
    lat: 52.4795,
    lng: 13.438,
    days: [1, 2, 3, 4, 5, 6, 0],
    startHour: 19,
    durationHours: 5,
    category: ['soul', 'funk', 'jazz'],
    vibe_tags: ['chill', 'openair', 'social', 'schick'],
    lineup: ['Rooftop Selectors'],
    priceMin: 4,
    priceMax: null,
    isFree: false,
    description:
      'Parkhausdach über Neukölln. Weite Sicht, warme Platten, kein Drang zum Tanzen — aber möglich.',
  },
  {
    slug: 'birgit-bier',
    title: 'Gartenparty: Disco & Italo',
    venue: 'Birgit & Bier',
    district: 'Kreuzberg',
    address: 'Schleusenufer 3, 10997 Berlin',
    lat: 52.4966,
    lng: 13.4479,
    days: [5, 6],
    startHour: 22,
    durationHours: 9,
    category: ['disco', 'italo-disco', 'house'],
    vibe_tags: ['tanzen', 'openair', 'schick'],
    lineup: ['Discodromo', 'Nadia Struiwigh'],
    priceMin: 15,
    priceMax: null,
    isFree: false,
    description: 'Karussell, Lichterketten, Freiluftfloor. Der Sommer-Klassiker am Kanal.',
  },
  {
    slug: 'about-blank-queer',
    title: 'Buttons: Queer Rave',
    venue: 'about blank',
    district: 'Friedrichshain',
    address: 'Markgrafendamm 24c, 10245 Berlin',
    lat: 52.504,
    lng: 13.468,
    days: [6],
    startHour: 23,
    durationHours: 14,
    category: ['queer', 'techno', 'electro'],
    vibe_tags: ['tanzen', 'underground', 'afterhour', 'social'],
    lineup: ['Ziúr', 'Lag Bo'],
    priceMin: 16,
    priceMax: null,
    isFree: false,
    description: 'Awareness-Team, Gartenfloor, kompromissloser Sound. Queere Nacht mit Haltung.',
  },
  {
    slug: 'tresor-globus',
    title: 'Tresor Nacht',
    venue: 'Tresor',
    district: 'Mitte',
    address: 'Köpenicker Straße 70, 10179 Berlin',
    lat: 52.5107,
    lng: 13.4198,
    days: [3, 5, 6],
    startHour: 0,
    durationHours: 10,
    category: ['techno', 'industrial', 'electro'],
    vibe_tags: ['tanzen', 'underground', 'dark'],
    lineup: ['Vril', 'DJ Bone'],
    priceMin: 15,
    priceMax: 20,
    isFree: false,
    description: 'Der Tunnel, der Nebel, die Stroboskope. Techno in seiner reduziertesten Form.',
  },
  {
    slug: 'prince-charles-hiphop',
    title: 'Rap Sundays',
    venue: 'Prince Charles',
    district: 'Kreuzberg',
    address: 'Prinzenstraße 85f, 10969 Berlin',
    lat: 52.501,
    lng: 13.4106,
    days: [0, 4],
    startHour: 22,
    durationHours: 6,
    category: ['hiphop', 'rnb', 'trap'],
    vibe_tags: ['tanzen', 'social', 'stylish'],
    lineup: ['DJ Nadir', 'Miss Cee'],
    priceMin: 12,
    priceMax: null,
    isFree: false,
    description:
      'Ehemaliges Schwimmbecken als Dancefloor. Kuratierte Rap-Sets, wenig Schnickschnack.',
  },
  {
    slug: 'monarch-electro',
    title: 'Monarch: Electro & EBM',
    venue: 'Monarch',
    district: 'Kreuzberg',
    address: 'Skalitzer Straße 134, 10999 Berlin',
    lat: 52.5006,
    lng: 13.4222,
    days: [2, 4, 5],
    startHour: 22,
    durationHours: 6,
    category: ['electro', 'ebm', 'wave'],
    vibe_tags: ['tanzen', 'underground', 'social'],
    lineup: ['Sarah Farina', 'Bad Stream'],
    priceMin: 8,
    priceMax: null,
    isFree: false,
    description: 'Ein Raum, große Fenster zur U1. Der ehrlichste Kleinclub der Stadt.',
  },
  {
    slug: 'arkaoda-experimental',
    title: 'Modular Nights',
    venue: 'Arkaoda',
    district: 'Neukölln',
    address: 'Karl-Marx-Platz 16, 12043 Berlin',
    lat: 52.483,
    lng: 13.429,
    days: [1, 3],
    startHour: 20,
    durationHours: 5,
    category: ['ambient', 'experimental', 'modular'],
    vibe_tags: ['chill', 'underground', 'live'],
    lineup: ['Grand River', 'Konvex'],
    priceMin: 10,
    priceMax: null,
    isFree: false,
    description: 'Sitzen, zuhören, staunen. Live-Elektronik ohne Vierviertel-Zwang.',
  },
  {
    slug: 'zig-zag-jazz',
    title: 'Jazzclub Session',
    venue: 'ZigZag Jazz Club',
    district: 'Schöneberg',
    address: 'Hauptstraße 89, 12159 Berlin',
    lat: 52.4762,
    lng: 13.3512,
    days: [1, 2, 3, 4],
    startHour: 20,
    durationHours: 4,
    category: ['jazz', 'nu-jazz', 'konzert'],
    vibe_tags: ['chill', 'live', 'schick'],
    lineup: ['Berlin Jazz Collective'],
    priceMin: 14,
    priceMax: 18,
    isFree: false,
    description: 'Kleine Bühne, gutes Essen, echte Jam-Session zum Schluss.',
  },
  {
    slug: 'mein-haus-am-see',
    title: 'Bar Session: Soul & Boogie',
    venue: 'Mein Haus am See',
    district: 'Mitte',
    address: 'Brunnenstraße 197, 10119 Berlin',
    lat: 52.5285,
    lng: 13.4009,
    days: [1, 2, 3, 4, 5, 6, 0],
    startHour: 21,
    durationHours: 7,
    category: ['soul', 'funk', 'pop'],
    vibe_tags: ['chill', 'social', 'bar'],
    lineup: ['Wechselnde Gäste'],
    priceMin: null,
    priceMax: null,
    isFree: true,
    description:
      'Tribünen-Sitzstufen, Kaffee bis Cocktail, immer offen. Kein Eintritt, kein Stress.',
  },
  {
    slug: 'buck-and-breck',
    title: 'Cocktail Hour im Hinterzimmer',
    venue: 'Buck and Breck',
    district: 'Mitte',
    address: 'Brunnenstraße 177, 10119 Berlin',
    lat: 52.5306,
    lng: 13.4023,
    days: [2, 3, 4, 5, 6],
    startHour: 19,
    durationHours: 5,
    category: ['pop', 'jazz'],
    vibe_tags: ['schick', 'chill', 'cocktail'],
    lineup: [],
    priceMin: null,
    priceMax: null,
    isFree: true,
    description: 'Vierzehn Plätze, klassische Drinks, gedämpftes Licht. Nur mit Reservierung.',
  },
  {
    slug: 'schmutziges-hobby',
    title: 'Drag Bingo',
    venue: 'Zum schmutzigen Hobby',
    district: 'Friedrichshain',
    address: 'Revaler Straße 99, 10245 Berlin',
    lat: 52.504,
    lng: 13.455,
    days: [1, 3, 6],
    startHour: 21,
    durationHours: 4,
    category: ['queer', 'drag', 'comedy'],
    vibe_tags: ['social', 'chill', 'kennenlernen'],
    lineup: ['Nina Queer'],
    priceMin: null,
    priceMax: null,
    isFree: true,
    description: 'Laut, schrill, herzlich. Bingo mit Drag-Moderation und günstigen Shots.',
  },
  {
    slug: 'astra-konzert',
    title: 'Astra Konzertabend',
    venue: 'Astra Kulturhaus',
    district: 'Friedrichshain',
    address: 'Revaler Straße 99, 10245 Berlin',
    lat: 52.5051,
    lng: 13.4497,
    days: [2, 3, 5],
    startHour: 20,
    durationHours: 4,
    category: ['indie', 'rock', 'konzert', 'pop'],
    vibe_tags: ['live', 'social'],
    lineup: ['Kraftklub', 'Support: Blond'],
    priceMin: 28,
    priceMax: 38,
    isFree: false,
    description: 'DDR-Charme, große Halle, laute Crowd. Danach Aftershow im Nebenraum.',
  },
  {
    slug: 'frannz-90s',
    title: '90s & 2000s Party',
    venue: 'Frannz Club',
    district: 'Prenzlauer Berg',
    address: 'Schönhauser Allee 36, 10435 Berlin',
    lat: 52.539,
    lng: 13.411,
    days: [5, 6],
    startHour: 23,
    durationHours: 6,
    category: ['pop', 'charts', 'hiphop'],
    vibe_tags: ['tanzen', 'social', 'kennenlernen'],
    lineup: ['DJ Retro'],
    priceMin: 10,
    priceMax: null,
    isFree: false,
    description: 'Mitsingen erlaubt, Gartenfloor im Sommer. Null Attitüde.',
  },
  {
    slug: 'loophole-experimental',
    title: 'Loophole: Noise & Lesung',
    venue: 'Loophole',
    district: 'Neukölln',
    address: 'Boddinstraße 60, 12053 Berlin',
    lat: 52.488,
    lng: 13.423,
    days: [1, 2, 4],
    startHour: 20,
    durationHours: 5,
    category: ['experimental', 'noise', 'lesung', 'performance'],
    vibe_tags: ['underground', 'chill', 'live'],
    lineup: ['Offene Bühne'],
    priceMin: 5,
    priceMax: null,
    isFree: false,
    description: 'Kellerraum, wechselndes Programm zwischen Lesung, Noise und Performance.',
  },
  {
    slug: 'ritter-butzke',
    title: 'Ritter Butzke Nacht',
    venue: 'Ritter Butzke',
    district: 'Kreuzberg',
    address: 'Ritterstraße 24, 10969 Berlin',
    lat: 52.5029,
    lng: 13.4083,
    days: [5, 6],
    startHour: 23,
    durationHours: 9,
    category: ['house', 'tech-house', 'techno'],
    vibe_tags: ['tanzen', 'schick'],
    lineup: ['Fritz Kalkbrenner', 'Nu Sky'],
    priceMin: 18,
    priceMax: 22,
    isFree: false,
    description: 'Alte Fabrik, vier Räume, viel Deko. Zugänglicher House für lange Nächte.',
  },
  {
    slug: 'sameheads-latin',
    title: 'Baile & Reggaeton',
    venue: 'Sameheads',
    district: 'Neukölln',
    address: 'Richardstraße 10, 12043 Berlin',
    lat: 52.4795,
    lng: 13.435,
    days: [4, 6],
    startHour: 23,
    durationHours: 7,
    category: ['latin', 'reggaeton', 'baile-funk'],
    vibe_tags: ['tanzen', 'social', 'underground'],
    lineup: ['La Fraîcheur', 'DJ Perreo'],
    priceMin: 8,
    priceMax: null,
    isFree: false,
    description: 'Ladenlokal oben, Schwitzkeller unten. Enge Tanzfläche, große Stimmung.',
  },
  {
    slug: 'privatclub-indie',
    title: 'Indie Disco',
    venue: 'Privatclub',
    district: 'Kreuzberg',
    address: 'Skalitzer Straße 85, 10997 Berlin',
    lat: 52.4989,
    lng: 13.4227,
    days: [5],
    startHour: 23,
    durationHours: 6,
    category: ['indie', 'indie-rock', 'post-punk', 'alternative'],
    vibe_tags: ['tanzen', 'social', 'kennenlernen'],
    lineup: ['DJ Anorak'],
    priceMin: 9,
    priceMax: null,
    isFree: false,
    description:
      'Von The Strokes bis Fontaines D.C. Wer Gitarren und Tanzen mag, ist hier richtig.',
  },
  {
    slug: 'saeaelchen-live',
    title: 'Säälchen Showcase',
    venue: 'Säälchen am Holzmarkt',
    district: 'Mitte',
    address: 'Holzmarktstraße 25, 10243 Berlin',
    lat: 52.5107,
    lng: 13.429,
    days: [2, 3, 4],
    startHour: 20,
    durationHours: 4,
    category: ['indie', 'ambient', 'konzert', 'jazz'],
    vibe_tags: ['live', 'chill', 'openair'],
    lineup: ['Newcomer-Showcase'],
    priceMin: 12,
    priceMax: null,
    isFree: false,
    description: 'Holzsaal am Wasser, sitzendes Publikum, danach Bier im Garten.',
  },
  {
    slug: 'ohm-ambient',
    title: 'OHM: Late Ambient',
    venue: 'OHM',
    district: 'Mitte',
    address: 'Köpenicker Straße 70, 10179 Berlin',
    lat: 52.5105,
    lng: 13.4192,
    days: [0, 3],
    startHour: 1,
    durationHours: 7,
    category: ['ambient', 'electro', 'experimental'],
    vibe_tags: ['afterhour', 'chill', 'underground'],
    lineup: ['Ambient Kollektiv'],
    priceMin: 10,
    priceMax: null,
    isFree: false,
    description: 'Ehemaliges Batteriehaus. Liegen, Nebel, langsame Frequenzen bis in den Morgen.',
  },
  {
    slug: 'kantine-quiz',
    title: 'Pub Quiz & Karaoke',
    venue: 'Kantine am Berghain',
    district: 'Friedrichshain',
    address: 'Am Wriezener Bahnhof, 10243 Berlin',
    lat: 52.5115,
    lng: 13.4425,
    days: [1, 2],
    startHour: 19,
    durationHours: 4,
    category: ['quiz', 'karaoke', 'comedy', 'pop'],
    vibe_tags: ['social', 'kennenlernen', 'chill'],
    lineup: ['Quizmaster Ben'],
    priceMin: 3,
    priceMax: null,
    isFree: false,
    description: 'Teams bis sechs Personen, danach offenes Karaoke. Anmelden lohnt sich.',
  },
];

/**
 * Deterministic demo programme used while the Supabase tables are still empty.
 * Rows are shaped exactly like the `events_feed` view.
 */
export function buildMockEvents(from: Date = new Date(), days = 21): EventRow[] {
  const today = startOfDay(from);
  const events: EventRow[] = [];

  for (let offset = 0; offset < days; offset += 1) {
    const nightDate = addDays(today, offset);
    const weekday = nightDate.getDay();

    for (const template of TEMPLATES) {
      if (!template.days.includes(weekday)) continue;

      const startsAt = new Date(nightDate);
      const dayShift = template.startHour < 6 ? 1 : 0;
      startsAt.setDate(startsAt.getDate() + dayShift);
      startsAt.setHours(template.startHour, 0, 0, 0);

      const endsAt = new Date(startsAt.getTime() + template.durationHours * 60 * 60 * 1000);

      events.push({
        id: `mock:${template.slug}:${offset}`,
        title: template.title,
        description_ours: template.description,
        starts_at: startsAt.toISOString(),
        ends_at: endsAt.toISOString(),
        doors_at: null,
        venue_name: template.venue,
        address: template.address,
        district: template.district,
        venue_homepage: null,
        price_min: template.priceMin,
        price_max: template.priceMax,
        is_free: template.isFree,
        ticket_url: null,
        source_url: null,
        category: template.category,
        vibe_tags: template.vibe_tags,
        lineup: template.lineup,
        image_url: null,
        status: 'active',
        latitude: template.lat,
        longitude: template.lng,
      });
    }
  }

  return events.sort(
    (left, right) => new Date(left.starts_at).getTime() - new Date(right.starts_at).getTime(),
  );
}
